basic moderation commands
S0raWasTaken/Serena pull request #1
Opened 2022-06-25 20:17 UTC by DRuppFv

Ainda tá bem shitty, eu só mandei agora pq vou sair. Hoje ainda faço mais comandos e expando esses aí, se eu encontrar algo. Manda lá no discord algo que tá mal feito que eu arrumo depois. Falô

2022-06-26 05:02 UTC, S0raWasTaken requested changes

2022-06-26 05:02 UTC, S0raWasTaken commented on src/commands/general/moderation.rs
> +        let kicked_user = &msg.mentions[0];
Um jeito melhor de lidar com isso seria usando o método `get()`, que te retornaria um `Option<User>`, mas eu prefiro que você use o `Clap` para lidar com os argumentos usando isso de exemplo: https://github.com/S0raWasTaken/Serena/blob/master/src/primitives.rs#L47#L74

2022-06-26 05:02 UTC, S0raWasTaken commented on src/commands/general/moderation.rs
> +            msg.reply(&ctx, "You can not ban yourself.").await?;
Já que você esqueceu de usar o `utils::handle_result`, você fica com uma bela dificuldade de gerenciar o erro que você vai mandar pro usuário e o erro que você vai retornar na função.
Dá uma olhada nesse exemplo: https://github.com/S0raWasTaken/Serena/blob/master/src/commands/general/prefix.rs#L49

O erro é retornado pra função e automaticamente já é mandado pro usuário formatado bonitinho, de acordo com a declaração de `handle_result` aqui: https://github.com/S0raWasTaken/Serena/blob/master/src/utils.rs#L24L38

E não esqueça de dar uma olhada no arquivo `src/utils.rs` pra você ver as funções que eu criei pra facilitar no desenvolvimento

2022-06-26 05:02 UTC, S0raWasTaken commented on src/commands/general/moderation.rs
> +        let banned_user = &msg.mentions[0];
O mesmo aqui

2022-06-26 05:02 UTC, S0raWasTaken commented on src/commands/general/moderation.rs
> +            };
E principalmente aqui, vi que você fez uma belíssima gambiarra pra isso funcionar. Faz o que eu te falei nas reviews anteriores que é sucesso

2022-06-26 05:03 UTC, DRuppFv commented on src/commands/general/moderation.rs
> +            };
KKKKKKk beleza foi mal por essa depressão em .rs aí que eu fiz

2022-06-28 10:01 UTC, S0raWasTaken commented
Vou aproveitar e fazer o comando de ban na tua branch e dar merge na master logo

2022-06-28 11:18 UTC, DRuppFv commented
> Vou aproveitar e fazer o comando de ban na tua branch e dar merge na master logo

Beleza, depois eu faço de unban

2022-06-28 13:15 UTC, S0raWasTaken commented
> > Vou aproveitar e fazer o comando de ban na tua branch e dar merge na master logo
> 
> Beleza, depois eu faço de unban

Ok, fiz umas modificações no teu comando de Kick e criei um comando de ban, dá uma olhada aí como tá.
Também simplifiquei os imports.

2022-06-28 13:16 UTC, S0raWasTaken commented
Assim q vc fizer o comando de unban, vou terminar a review e dar merge

2022-06-29 22:28 UTC, DRuppFv commented
> Assim q vc fizer o comando de unban, vou terminar a review e dar merge

unban feito

2022-06-30 14:12 UTC, S0raWasTaken commented
Pronto, acho que já deve estar pronto para merge, vou esperar os checks terminarem e já mandar pra `master`. 
Valeu pela contribuição @DRuppFv!

2022-06-30 14:13 UTC, S0raWasTaken approved these changes

2022-06-30 18:25 UTC, DRuppFv commented
> Pronto, acho que já deve estar pronto para merge, vou esperar os checks terminarem e já mandar pra `master`. Valeu pela contribuição @DRuppFv!


Se tu continuar com o projeto seriamente, agora que eu pelo menos sei lidar com clap, eu vou continuar mandando umas pull request aí.

2022-07-01 20:20 UTC, merged